server:
  port: 5000
spring:
  application:
    name: gateway-server
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
zuul:
  routes:
    api-a:
      path: /user-api/**
      serviceId: user-server